# Generated by Django 4.1.3 on 2023-09-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportthebrosapi', '0002_alter_post_tag_id_alter_posttag_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_id',
        ),
    ]
